language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-amp-publish-plugin' ]; then cd .. && eval "mv $currentfolder generator-amp-publish-plugin" && cd generator-amp-publish-plugin; fi

